// src/app/api/shifts/import/route.ts
import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/api-auth";
import { badRequest, ok, parsePagination, serializeShiftImportBatch, serverError } from "@/lib/api-utils";
import { importShiftsSchema } from "@/lib/schemas/shift";
import { applyShiftImport, parseImportContent } from "@/lib/shift-import";

/**
 * GET /api/shifts/import
 * Lists past import batches, newest first — the "batch history" panel.
 */
export async function GET(request: NextRequest) {
  const auth = await requirePermission(request, "shifts", "view");
  if ("error" in auth) return auth.error;

  try {
    const { searchParams } = new URL(request.url);
    const { offset, limit } = parsePagination(searchParams, 20, 100);

    const [batches, total] = await Promise.all([
      prisma.shiftImportBatch.findMany({ orderBy: { createdAt: "desc" }, skip: offset, take: limit }),
      prisma.shiftImportBatch.count(),
    ]);

    return ok({
      data: batches.map(serializeShiftImportBatch),
      meta: { total, offset, limit, hasMore: offset + batches.length < total },
    });
  } catch (error) {
    return serverError(error);
  }
}

/**
 * POST /api/shifts/import
 * Imports a weekly schedule generated by the external scheduler system.
 * Body: { fileName, content } — content is raw CSV text or a JSON array of
 * row objects (columns: employee_code, station_code, date, shift, role,
 * pos_machine_code?). One bad row doesn't abort the batch — every row is
 * validated and resolved independently, with per-row errors returned
 * alongside whatever succeeded.
 */
export async function POST(request: NextRequest) {
  const auth = await requirePermission(request, "shifts", "edit");
  if ("error" in auth) return auth.error;

  try {
    const body = await request.json();
    const parsed = importShiftsSchema.safeParse(body);
    if (!parsed.success) return badRequest("Invalid request body.", parsed.error.flatten());

    let rows: Record<string, string>[];
    try {
      rows = parseImportContent(parsed.data.fileName, parsed.data.content);
    } catch (e) {
      return badRequest(e instanceof Error ? e.message : "Could not parse the uploaded file.");
    }
    if (rows.length === 0) return badRequest("The uploaded file has no rows.");

    const { result, batchId } = await applyShiftImport(parsed.data.fileName, rows, auth.session.adminUserId);
    return ok({ batchId, ...result });
  } catch (error) {
    return serverError(error);
  }
}
